# Default configuration for Domain Agnostic Recommender System

# Environment settings
environment: development
debug: true

# Paths
data_dir: ./data
artifacts_dir: ./artifacts
logs_dir: ./logs

# API settings
api_host: 0.0.0.0
api_port: 8000

# Model settings
default_factors: 100
default_iterations: 15
evaluation_metrics:
  - map_at_k
  - coverage
  - novelty
  - diversity
